name: Maven Build

on:
  workflow_call:
    inputs:
      jdk-distribution:
        required: false
        type: string
        default: corretto
      jdk-version:
        required: false
        type: number
        default: 21
      pom-file:
        required: false
        type: string
        default: ./pom.xml
      mvn-goals:
        required: false
        type: string
        default: clean package -DskipTests
      mvn-opts:
        required: false
        type: string
        default: -Xmx1024m
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maven Build
        uses: kvncont/maven-action@main
        with:
          jdk-distribution: ${{ inputs.jdk-distribution }}
          jdk-version: ${{ inputs.jdk-version }}
          pom-file: ${{ inputs.pom-file }}
          maven-goals: ${{ inputs.mvn-goals }}
          maven-opts: ${{ inputs.mvn-opts }}
      
      - name: Docker Build & Push
        uses: kvncont/docker-action@main
        with:
          dockerfile: Dockerfile
          context: .
          tags: latest
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
